=== JaneliaSciComp/tmog/config/transmogrifier_config.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="inputFileFilterType">
        <xs:attribute name="patternString" type="xs:string"/>
        <xs:attribute name="patternGroupNumber" type="xs:positiveInteger"/>
        <xs:attribute name="excludeQueryUrl" type="xs:anyURI"/>
        <xs:attribute name="includeQueryUrl" type="xs:anyURI"/>
        <xs:attribute name="recursiveSearch" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="inputFileSorterType">
        <xs:attribute name="sortAlgorithm" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="outputDirectoryType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="path" type="pathType"/>
            <xs:element name="renameFieldValue" type="renameFieldValueType"/>
            <xs:element name="sourceFileModificationTime"
                        type="sourceFileModificationTimeType"/>
        </xs:choice>
        <xs:attribute name="basePath" type="xs:string"/>
        <xs:attribute name="derivedFromEarliestModifiedFile" type="xs:boolean"/>
        <xs:attribute name="fileModeReadOnly" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="pathType">
        <xs:attribute name="path" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="renameFieldValueType">
        <xs:attribute name="fieldDisplayName" type="xs:string"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="sourceFileModificationTimeType">
        <xs:attribute name="datePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="propertyType">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="pluginType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="property" type="propertyType"/>
        </xs:sequence>
        <xs:attribute name="className" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="pluginsType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="rowValidator" type="pluginType" />
            <xs:element name="rowListener" type="pluginType" />
            <xs:element name="sessionListener" type="pluginType" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="staticType">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="numberType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="staticDefault" type="staticDefaultType"
                        minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="minimumValue" type="xs:integer"/>
        <xs:attribute name="maximumValue" type="xs:integer"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="decimalType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="staticDefault" type="staticDefaultType"
                        minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="minimumValue" type="xs:integer"/>
        <xs:attribute name="maximumValue" type="xs:integer"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="textType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="staticDefault" type="staticDefaultType"
                        minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="minimumLength" type="xs:integer"/>
        <xs:attribute name="maximumLength" type="xs:integer"/>
        <xs:attribute name="pattern" type="xs:string"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="dateType">
        <xs:sequence>
            <xs:element name="sourceFileDateDefault" type="sourceFileDateDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="datePattern" type="xs:string"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="wellType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="formFactor" type="xs:integer"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="validValueType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="default" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="validValueListType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="validValue" type="validValueType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="pluginDataType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="format" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="fileModificationTimeType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="datePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="runTimeType">
        <xs:attribute name="datePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="fileExtensionType">
        <xs:attribute name="markedForTask" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="targetNameType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="fileRelativePathType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="visible" type="xs:boolean"/>
    </xs:complexType>

    <xs:simpleType name="matchType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="name"/>
            <xs:enumeration value="path"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="sourceFileDefaultType">
        <xs:attribute name="pattern" type="xs:string"/>
        <xs:attribute name="matchType" type="matchType"/>
    </xs:complexType>

    <xs:complexType name="sourceFileDateDefaultType">
        <xs:attribute name="pattern" type="xs:string"/>
        <xs:attribute name="matchType" type="matchType"/>
        <xs:attribute name="fromDatePattern" type="xs:string"/>
        <xs:attribute name="toDatePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="staticDefaultType">
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="projectType">
        <xs:sequence>

            <xs:element name="inputFileFilter" type="inputFileFilterType" minOccurs="0"/>

            <xs:element name="inputFileSorter" type="inputFileSorterType" minOccurs="0"/>

            <xs:element name="outputDirectory" type="outputDirectoryType" minOccurs="0"/>

            <xs:element name="plugins" type="pluginsType" minOccurs="0"/>

            <xs:element name="dataFields" maxOccurs="1">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="separator" type="staticType"/>
                        <xs:element name="static" type="staticType"/>
                        <xs:element name="number" type="numberType"/>
                        <xs:element name="decimal" type="decimalType"/>
                        <xs:element name="text" type="textType"/>
                        <xs:element name="date" type="dateType"/>
                        <xs:element name="well" type="wellType"/>
                        <xs:element name="validValueList"
                                    type="validValueListType"/>
                        <xs:element name="pluginData" type="pluginDataType"/>
                        <xs:element name="fileModificationTime"
                                    type="fileModificationTimeType"/>
                        <xs:element name="runTime" type="runTimeType"/>
                        <xs:element name="fileExtension"
                                    type="fileExtensionType"/>
                        <xs:element name="targetName"
                                    type="targetNameType"/>
                        <xs:element name="fileRelativePath"
                                    type="fileRelativePathType"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="default" type="xs:boolean"/>
        <xs:attribute name="taskName" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="globalType">
        <xs:attribute name="minimumVersion" type="xs:string"/>
    </xs:complexType>

    <xs:element name="transmogrifierConfiguration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="global" type="globalType" minOccurs="0" maxOccurs="1"/>
                <xs:element name="project" type="projectType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== JaneliaSciComp/tmog/config/transmogrifier_config_rubin_wu.xml
<?xml version="1.0"?>

<transmogrifierConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="transmogrifier_config.xsd">

    <global minimumVersion="2.4.8" frameSizePercentage="95"/>

    <project name="Rubin Lab: Ming's Images (MW_*)" default="true">

        <inputFileSorter sortAlgorithm="LNumber" />

        <outputDirectory basePath="[\\dm10.isln.janelia.org\rubindata|/groups/rubin/data1/rubinlab]\Ming\confocalStacks"
                         derivedFromEarliestModifiedFile="true"/>

        <plugins>

            <rowValidator className="org.janelia.it.ims.tmog.plugin.HttpResourceValidator">
                <property name="serviceUrl" value="http://sage.int.janelia.org/sage-ws/lines/rubin/${Line 1}.janelia-sage"/>
                <property name="testUrl" value="http://sage.int.janelia.org/sage-ws/lines/rubin/GMR_10A01_AE_01.janelia-sage"/>
                <property name="errorMessage" value="There is no 'rubin' lab line named '${Line 1}' in the SAGE database."/>
                <property name="clearCacheDuration" value="6000000"/><!-- 100 minutes -->
            </rowValidator>

            <rowValidator className="org.janelia.it.ims.tmog.plugin.HttpResourceValidator">
                <property name="serviceUrl" value="http://sage.int.janelia.org/sage-ws/lines/rubin/${Line 2}.janelia-sage"/>
                <property name="testUrl" value="http://sage.int.janelia.org/sage-ws/lines/rubin/GMR_10A01_AE_01.janelia-sage"/>
                <property name="errorMessage" value="There is no 'rubin' lab line named '${Line 2}' in the SAGE database."/>
                <property name="clearCacheDuration" value="6000000"/><!-- 100 minutes -->
            </rowValidator>

            <rowListener className="org.janelia.it.ims.tmog.plugin.imagedb.ImageDataPlugin">
                <property name="db.config.key" value="sage"/>
                <property name="family" value="$STATIC:rubin_wu"/>
                <property name="lab" value="$STATIC:rubin"/>
                <property name="line" value="${Line 1}"/>
                <property name="uas_reporter" value="UAS Reporter"/>
                <property name="mounting_protocol" value="Tissue Mounting Protocol"/>
                <property name="tissue_orientation" value="Tissue Orientation"/>
            </rowListener>

        </plugins>

        <dataFields>
            <separator value="MW-"/>
            <text displayName="Line 1" required="true" displayWidth="150"
                  pattern="GMR_[0-9A-Z\_]++">
            </text>
            <separator value="-"/>
            <text displayName="Line 2" required="true" displayWidth="150"
                  pattern="GMR_[0-9A-Z\_]++">
            </text>

            <separator value="-"/>
            <validValueList displayName="Gender" required="true">
                <validValue displayName="m: Male" value="m"/>
                <validValue displayName="f: Female" value="f"/>
                <validValue displayName="x: Not Defined" value="x"/>
            </validValueList>
            <validValueList displayName="Age" required="true">
                <validValue displayName="X00: undefined" value="X00"/>
                <validValue displayName="P01: Prepupa" value="P01"/>
                <validValue displayName="P02: Pupa" value="P02"/>
                <validValue displayName="E01: Embryonic Stage 1" value="E01"/>
                <validValue displayName="E02: Embryonic Stage 2" value="E02"/>
                <validValue displayName="E03: Embryonic Stage 3" value="E03"/>
                <validValue displayName="E04: Embryonic Stage 4" value="E04"/>
                <validValue displayName="E05: Embryonic Stage 5" value="E05"/>
                <validValue displayName="E06: Embryonic Stage 6" value="E06"/>
                <validValue displayName="E07: Embryonic Stage 7" value="E07"/>
                <validValue displayName="E08: Embryonic Stage 8" value="E08"/>
                <validValue displayName="E09: Embryonic Stage 9" value="E09"/>
                <validValue displayName="E10: Embryonic Stage 10" value="E10"/>
                <validValue displayName="E11: Embryonic Stage 11" value="E11"/>
                <validValue displayName="E12: Embryonic Stage 12" value="E12"/>
                <validValue displayName="E13: Embryonic Stage 13" value="E13"/>
                <validValue displayName="E14: Embryonic Stage 14" value="E14"/>
                <validValue displayName="E15: Embryonic Stage 15" value="E15"/>
                <validValue displayName="E16: Embryonic Stage 16" value="E16"/>
                <validValue displayName="E17: Embryonic Stage 17" value="E17"/>
                <validValue displayName="L01: First Instar" value="L01"/>
                <validValue displayName="L02: Second Instar" value="L02"/>
                <validValue displayName="L03: Third Instar" value="L03"/>
                <validValue displayName="A01: Day 1-5" value="A01"/>
                <validValue displayName="A02: Day 6-10" value="A02"/>
                <validValue displayName="A03: Day 11-15" value="A03"/>
                <validValue displayName="A04: Day 16-20" value="A04"/>
                <validValue displayName="A05: Day 21-25" value="A05"/>
                <validValue displayName="A06: Day 26-30" value="A06"/>
            </validValueList>
            <validValueList displayName="Area" required="true">
                <validValue displayName="s: Salivary Gland" value="s"/>
                <validValue displayName="b: Brain" value="b"/>
                <validValue displayName="v: Ventral Nerve Cord" value="v"/>
            </validValueList>
            <separator value="-"/>
            <number displayName="Concentration" required="true"
                    minimumValue="0" maximumValue="5000"  padFormat="40">
                <sourceFileDefault pattern=".+L\d\d??_.*-(\d+).*#.*"/>                
            </number>
            <separator value="-"/>
            <runTime datePattern="yyyyMMddHHmmssSSS"/>
            <separator value=".lsm"/>

            <!--
             These values are collected for the SAGE database but are not
             included as components of the file name (markedForTask="false").
             -->
            <validValueList displayName="Tissue Mounting Protocol" required="true"
                            markedForTask="false">
                <validValue value="Glycerol-Based Mounting" default="true"/>
                <validValue value="DPX Mounting"/>
            </validValueList>
            <cvTermList displayName="Tissue Orientation" required="true"
                        markedForTask="false"
                        serviceUrl="http://sage.int.janelia.org/sage-ws/cvs/tissue_orientation"
                        displayNamePrefixedForValues="false">
            </cvTermList>
            <validValueList displayName="UAS Reporter" required="true"
                            markedForTask="false">
                <validValue value="UAS_IVS-mCD8_3_0007" default="true"/>
                <validValue value="UAS_mCD8_2_0006"/>
                <validValue value="LexAop_IVS-myr_3_0008"/>
            </validValueList>
        </dataFields>

    </project>

</transmogrifierConfiguration>

=== JaneliaSciComp/tmog/config/transmogrifier_config_simpson_lex_a.xml
<?xml version="1.0"?>

<transmogrifierConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="transmogrifier_config.xsd">

    <global minimumVersion="2.4.7"/>

    <project name="Simpson Lab: LexA Lines (JHS_*)" default="true">

        <inputFileFilter patternString=".+\.lsm"
                         recursiveSearch="true"/>

        <inputFileSorter sortAlgorithm="LNumber" />

        <outputDirectory>
            <path path="\\dm10.isln.janelia.org\simpsonmicro\Lex_confocal_stacks\" />
            <renameFieldValue fieldDisplayName="Line"/>
        </outputDirectory>

        <plugins>
            <sessionListener className="org.janelia.it.ims.tmog.plugin.SessionSummaryFileWriter">
                <property name="directory" value="\\dm10.isln.janelia.org\simpsonmicro\tmog\summaries\LexA"/>
            </sessionListener>
        </plugins>

        <dataFields>
            <separator value="JHS_"/>

            <text displayName="Line" required="true"
                  pattern="LexA[0-9A-Za-z]++">
                <sourceFileDefault pattern=".*[/\\\\](LexA[0-9A-Za-z]++)[/\\\\].*\.lsm"
                                   matchType="path"/>
            </text>

            <date displayName="Capture Date" required="true"
                  datePattern="yyyyMMdd" prefix="_">
                <sourceFileDateDefault pattern="^(\d\d?-\d\d?-\d\d){1}_.*"
                                       fromDatePattern="MM-dd-yy"
                                       toDatePattern="yyyyMMdd"/>
            </date>

            <validValueList displayName="Organ" required="true" prefix="_">
                <validValue displayName="b: Brain" value="b"/>
                <validValue displayName="l: Larva" value="l"/>
                <validValue displayName="t: Thorax" value="t"/>
            </validValueList>

            <runTime datePattern="'_'yyyyMMddHHmmssSSS"/>

            <fileExtension/>
        </dataFields>

    </project>

</transmogrifierConfiguration>

=== JaneliaSciComp/tmog/config/transmogrifier_config_heberlein.xml
<?xml version="1.0"?>

<transmogrifierConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="transmogrifier_config.xsd">

    <global minimumVersion="2.9.6" frameSizePercentage="95"/>

    <project name="Heberlein - Central Brain (UAHC*)" default="true">

        <inputFileSorter sortAlgorithm="Number"
                         patternString=".*_(L)(\d++)(\.lsm)"/>

        <outputDirectory basePath="[\\dm11.janelia.priv|/groups/heberlein]/heberleinlab/image/heberlein_central_brain/confocalStacks"
                         derivedFromEarliestModifiedFile="true"/>

        <plugins>

            <rowListener className="org.janelia.it.ims.tmog.plugin.imagedb.ImageSequencePlugin">
                <property name="db.config.key" value="sage" />
                <property name="image_number" value="urn:lsid:janelia.org:heberlein_central_brain:image_number" />
            </rowListener>

            <rowListener className="org.janelia.it.ims.tmog.plugin.imagedb.ImageDataPlugin">
                <property name="db.config.key" value="sage"/>
                <property name="lab" value="$STATIC:heberlein"/>
                <property name="family" value="$STATIC:heberlein_central_brain"/>
                <property name="line" value="Line"/>
                <property name="effector" value="Effector"/>
                <property name="tile" value="Tile"/>
                <property name="condition" value="Condition"/>
                <property name="data_set" value="Data Set"/>
                <property name="channel_spec" value="Channel Specification"/>
                <property name="microscope_filename"/>
            </rowListener>

            <!--
                  The companion file listener (for log files) should be the
                  last defined plug-in to ensure that log files are only
                  copied if the source lsm processing succeeds.
            -->
            <rowListener className="org.janelia.it.ims.tmog.plugin.CompanionFileRowListener" >
                <property name="sourceSuffix" value=".lsm"/>
                <property name="companionSuffix" value="_log.csv"/>
                <property name="deleteAfterCopy" value="true"/>
            </rowListener>

        </plugins>

        <dataFields>

            <separator value="UAHC_"/>
            <runTime datePattern="yyyyMMddHHmmssSSS" />
            <separator value="_"/>
            <pluginData displayName="image_number"/>
            <separator value=".lsm"/>

            <!--
             These values are collected for storage but are not
             included as components of the file name (markedForTask="false").
             -->

            <webServiceList displayName="Line" required="true"
                            markedForTask="false"
                            valueCreationPath="*/line"
                            relativeActualValuePath="name"
                            relativeValueDisplayNamePath="name"
                            serviceUrl="http://sage.int.janelia.org/sage-ws/lines/forMultipleLabs.janelia-sage?lab=heberlein"
                            autoComplete="true">
            </webServiceList>

            <!-- filtered list from http://sage.int.janelia.org/sage-ws/cvs/effector -->
            <validValueList displayName="Effector" required="true"
                            autoComplete="true"
                            markedForTask="false">
                <validValue displayName="57C10Lwt_attp8_3stop1" value="57C10Lwt_attp8_3stop1"/>
                <validValue displayName="w1118(5905); +; pJFRC12-10XUAS-IVS-myr::GFP (V) $" value="UAS_IVS_myr_3_0009"/>
            </validValueList>

            <validValueList displayName="Tile" required="true"
                            autoComplete="true"
                            markedForTask="false">
                <validValue displayName="Ventral" value="ventral"/>
                <validValue displayName="Left Dorsal" value="left_dorsal"/>
                <validValue displayName="Right Dorsal" value="right_dorsal"/>
            </validValueList>


            <validValueList displayName="Condition" required="true"
                            autoComplete="true"
                            markedForTask="false">
                <validValue value="extracted"/>
                <validValue value="delineates"/>
                <validValue value="mated"/>
                <validValue value="rejected"/>
            </validValueList>

            <webServiceList displayName="Data Set" required="true"
                            markedForTask="false"
                            valueCreationPath="*/dataSet"
                            relativeActualValuePath="dataSetIdentifier"
                            relativeValueDisplayNamePath="dataSetIdentifier"
                            serviceUrl="http://jacs.int.janelia.org:8180/rest-v1/dataSet?user=heberleinlab&amp;includeOnlySageSync=true"
                            autoComplete="true">
            </webServiceList>

            <text displayName="Channel Specification" required="true"
                  markedForTask="false"
                  pattern="s*rs*">
            </text>

        </dataFields>

    </project>

</transmogrifierConfiguration>
