=== JaneliaSciComp/tmog/config/transmogrifier_config.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="inputFileFilterType">
        <xs:attribute name="patternString" type="xs:string"/>
        <xs:attribute name="patternGroupNumber" type="xs:positiveInteger"/>
        <xs:attribute name="excludeQueryUrl" type="xs:anyURI"/>
        <xs:attribute name="includeQueryUrl" type="xs:anyURI"/>
        <xs:attribute name="recursiveSearch" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="inputFileSorterType">
        <xs:attribute name="sortAlgorithm" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="outputDirectoryType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="path" type="pathType"/>
            <xs:element name="renameFieldValue" type="renameFieldValueType"/>
            <xs:element name="sourceFileModificationTime"
                        type="sourceFileModificationTimeType"/>
        </xs:choice>
        <xs:attribute name="basePath" type="xs:string"/>
        <xs:attribute name="derivedFromEarliestModifiedFile" type="xs:boolean"/>
        <xs:attribute name="fileModeReadOnly" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="pathType">
        <xs:attribute name="path" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="renameFieldValueType">
        <xs:attribute name="fieldDisplayName" type="xs:string"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="sourceFileModificationTimeType">
        <xs:attribute name="datePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="propertyType">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="pluginType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="property" type="propertyType"/>
        </xs:sequence>
        <xs:attribute name="className" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="pluginsType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="rowValidator" type="pluginType" />
            <xs:element name="rowListener" type="pluginType" />
            <xs:element name="sessionListener" type="pluginType" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="staticType">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="numberType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="staticDefault" type="staticDefaultType"
                        minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="minimumValue" type="xs:integer"/>
        <xs:attribute name="maximumValue" type="xs:integer"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="decimalType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="staticDefault" type="staticDefaultType"
                        minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="minimumValue" type="xs:integer"/>
        <xs:attribute name="maximumValue" type="xs:integer"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="textType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="staticDefault" type="staticDefaultType"
                        minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="minimumLength" type="xs:integer"/>
        <xs:attribute name="maximumLength" type="xs:integer"/>
        <xs:attribute name="pattern" type="xs:string"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="dateType">
        <xs:sequence>
            <xs:element name="sourceFileDateDefault" type="sourceFileDateDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="datePattern" type="xs:string"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="wellType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="formFactor" type="xs:integer"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="validValueType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="default" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="validValueListType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="validValue" type="validValueType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="pluginDataType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="format" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="fileModificationTimeType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="datePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="runTimeType">
        <xs:attribute name="datePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="fileExtensionType">
        <xs:attribute name="markedForTask" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="targetNameType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="fileRelativePathType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="visible" type="xs:boolean"/>
    </xs:complexType>

    <xs:simpleType name="matchType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="name"/>
            <xs:enumeration value="path"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="sourceFileDefaultType">
        <xs:attribute name="pattern" type="xs:string"/>
        <xs:attribute name="matchType" type="matchType"/>
    </xs:complexType>

    <xs:complexType name="sourceFileDateDefaultType">
        <xs:attribute name="pattern" type="xs:string"/>
        <xs:attribute name="matchType" type="matchType"/>
        <xs:attribute name="fromDatePattern" type="xs:string"/>
        <xs:attribute name="toDatePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="staticDefaultType">
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="projectType">
        <xs:sequence>

            <xs:element name="inputFileFilter" type="inputFileFilterType" minOccurs="0"/>

            <xs:element name="inputFileSorter" type="inputFileSorterType" minOccurs="0"/>

            <xs:element name="outputDirectory" type="outputDirectoryType" minOccurs="0"/>

            <xs:element name="plugins" type="pluginsType" minOccurs="0"/>

            <xs:element name="dataFields" maxOccurs="1">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="separator" type="staticType"/>
                        <xs:element name="static" type="staticType"/>
                        <xs:element name="number" type="numberType"/>
                        <xs:element name="decimal" type="decimalType"/>
                        <xs:element name="text" type="textType"/>
                        <xs:element name="date" type="dateType"/>
                        <xs:element name="well" type="wellType"/>
                        <xs:element name="validValueList"
                                    type="validValueListType"/>
                        <xs:element name="pluginData" type="pluginDataType"/>
                        <xs:element name="fileModificationTime"
                                    type="fileModificationTimeType"/>
                        <xs:element name="runTime" type="runTimeType"/>
                        <xs:element name="fileExtension"
                                    type="fileExtensionType"/>
                        <xs:element name="targetName"
                                    type="targetNameType"/>
                        <xs:element name="fileRelativePath"
                                    type="fileRelativePathType"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="default" type="xs:boolean"/>
        <xs:attribute name="taskName" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="globalType">
        <xs:attribute name="minimumVersion" type="xs:string"/>
    </xs:complexType>

    <xs:element name="transmogrifierConfiguration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="global" type="globalType" minOccurs="0" maxOccurs="1"/>
                <xs:element name="project" type="projectType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== JaneliaSciComp/tmog/config/transmogrifier_config_flylight_dickson.xml
<?xml version="1.0"?>

<transmogrifierConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="transmogrifier_config.xsd">

    <global minimumVersion="3.0.7" frameSizePercentage="95"/>

    <project name="Fly Light: Dickson Images (BJD_*)" default="true">

        <inputFileSorter sortAlgorithm="LNumber" />

        <outputDirectory basePath="[\\dm11.janelia.priv|/groups/flylight]/flylight/dickson/confocalStacks"
                         derivedFromEarliestModifiedFile="true"/>

        <plugins>

            <rowValidator className="org.janelia.it.wip.WipDataPlugin">
                <property name="batchNameFieldName" value="Batch Name"/>
                <property name="batchNumberFieldName" value="Batch Number"/>
                <property name="batchColorFieldName" value="Batch Color"/>
            </rowValidator>

            <rowListener className="org.janelia.it.wip.WipDataPlugin">
                <property name="batchNameFieldName" value="Batch Name"/>
                <property name="batchNumberFieldName" value="Batch Number"/>
                <property name="batchColorFieldName" value="Batch Color"/>
            </rowListener>

            <rowListener className="org.janelia.it.ims.tmog.plugin.imagedb.ImageDataPlugin">
                <property name="db.config.key" value="sage"/>
                <property name="lab" value="$STATIC:dickson"/>
                <property name="family" value="$STATIC:dickson"/>
                <property name="imaging_project" value="$STATIC:broad_expression_patterns"/>
                <property name="effector" value="UAS Reporter"/>
                <property name="line" value="Line"/>
                <property name="created_by" value="Imager"/>
                <property name="renamed_by" value="Renamer"/>
                <property name="class" value="Class"/>
                <property name="ihc_batch" value="Batch Name"/>
                <property name="mounting_protocol" value="Tissue Mounting Protocol"/>
                <property name="tissue_orientation" value="Tissue Orientation"/>
            </rowListener>

        </plugins>

        <dataFields>

            <!-- lines should all start with BJD -->
            <webServiceList displayName="Line" required="true"
                            valueCreationPath="*/line"
                            relativeActualValuePath="name"
                            relativeValueDisplayNamePath="name"
                            serviceUrl="http://sage.int.janelia.org/sage-ws/lines/forMultipleLabs.janelia-sage?lab=dickson"
                            autoComplete="true">
            </webServiceList>

            <separator value="_00-"/>

            <validValueList displayName="Gender" required="true">
                <validValue displayName="m: Male" value="m"/>
                <validValue displayName="f: Female" value="f"/>
                <validValue displayName="x: Not Defined" value="x"/>
            </validValueList>

            <validValueList displayName="Age" required="true">
                <validValue displayName="X00: undefined" value="X00"/>
                <validValue displayName="P01: Prepupa" value="P01"/>
                <validValue displayName="P02: Pupa" value="P02"/>
                <validValue displayName="E01: Embryonic Stage 1" value="E01"/>
                <validValue displayName="E02: Embryonic Stage 2" value="E02"/>
                <validValue displayName="E03: Embryonic Stage 3" value="E03"/>
                <validValue displayName="E04: Embryonic Stage 4" value="E04"/>
                <validValue displayName="E05: Embryonic Stage 5" value="E05"/>
                <validValue displayName="E06: Embryonic Stage 6" value="E06"/>
                <validValue displayName="E07: Embryonic Stage 7" value="E07"/>
                <validValue displayName="E08: Embryonic Stage 8" value="E08"/>
                <validValue displayName="E09: Embryonic Stage 9" value="E09"/>
                <validValue displayName="E10: Embryonic Stage 10" value="E10"/>
                <validValue displayName="E11: Embryonic Stage 11" value="E11"/>
                <validValue displayName="E12: Embryonic Stage 12" value="E12"/>
                <validValue displayName="E13: Embryonic Stage 13" value="E13"/>
                <validValue displayName="E14: Embryonic Stage 14" value="E14"/>
                <validValue displayName="E15: Embryonic Stage 15" value="E15"/>
                <validValue displayName="E16: Embryonic Stage 16" value="E16"/>
                <validValue displayName="E17: Embryonic Stage 17" value="E17"/>
                <validValue displayName="L01: First Instar" value="L01"/>
                <validValue displayName="L02: Second Instar" value="L02"/>
                <validValue displayName="L03: Third Instar" value="L03"/>
                <validValue displayName="A01: Day 1-5" value="A01"/>
                <validValue displayName="A02: Day 6-10" value="A02"/>
                <validValue displayName="A03: Day 11-15" value="A03"/>
                <validValue displayName="A04: Day 16-20" value="A04"/>
                <validValue displayName="A05: Day 21-25" value="A05"/>
                <validValue displayName="A06: Day 26-30" value="A06"/>
            </validValueList>

            <validValueList displayName="Area" required="true">
                <validValue displayName="s: Salivary Gland" value="s"/>
                <validValue displayName="b: Brain" value="b"/>
                <validValue displayName="v: Ventral Nerve Cord" value="v"/>
            </validValueList>

            <separator value="_C"/>
            <fileModificationTime displayName="Capture Date" datePattern="yyMMdd" />
            <separator value="_"/>
            <runTime datePattern="yyyyMMddHHmmssSSS"/>
            <separator value=".lsm"/>

            <!--
             These values are collected for the SAGE database but are not
             included as components of the file name (markedForTask="false").
             -->
            <number displayName="Batch Number" required="true"
                    minimumValue="80" maximumValue="600"
                    markedForTask="false" />

            <validValueList displayName="Batch Color" required="true"
                            markedForTask="false">
                <validValue value="red"/>
                <validValue value="tan"/>
                <validValue value="purple"/>
                <validValue value="blue"/>
                <validValue value="white"/>
                <validValue value="pink"/>
                <validValue value="gray"/>
                <validValue value="green"/>
                <validValue value="yellow"/>
                <validValue value="orange"/>
            </validValueList>

            <pluginData displayName="Batch Name" markedForTask="false" />

            <validValueList displayName="Tissue Mounting Protocol" required="true"
                            markedForTask="false">
                <validValue value="Glycerol-Based Mounting" default="true"/>
                <validValue value="DPX Mounting"/>
            </validValueList>

            <cvTermList displayName="Tissue Orientation" required="true"
                        markedForTask="false"
                        serviceUrl="http://sage.int.janelia.org/sage-ws/cvs/tissue_orientation"
                        displayNamePrefixedForValues="false">
                <staticDefault value="face_up"/>
            </cvTermList>

            <validValueList displayName="UAS Reporter" required="true"
                            markedForTask="false">
                <validValue value="UAS_IVS-mCD8_3_0007" default="true"/>
                <validValue value="UAS_mCD8_2_0006"/>
                <validValue value="LexAop_IVS-myr_3_0008"/>
            </validValueList>

            <cvTermList displayName="Imager" required="true"
                        markedForTask="false"
                        autoComplete="true"
                        serviceUrl="http://sage.int.janelia.org/sage-ws/cvs/imager">
            </cvTermList>

            <cvTermList displayName="Renamer" required="true"
                        markedForTask="false"
                        autoComplete="true"
                        serviceUrl="http://sage.int.janelia.org/sage-ws/cvs/imager"
                        sharedForAllSessionFiles="true">
            </cvTermList>

            <validValueList displayName="Class" required="false"
                            markedForTask="false">
                <validValue displayName="Screening" value="Screening" default="true"/>
                <validValue displayName="Rework" value="Rework"/>
            </validValueList>

        </dataFields>

    </project>

</transmogrifierConfiguration>

=== JaneliaSciComp/tmog/config/transmogrifier_config_rubin_wu_split.xml
<?xml version="1.0"?>

<transmogrifierConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="transmogrifier_config.xsd">

    <global minimumVersion="2.6.0" frameSizePercentage="95"/>

    <project name="Rubin Lab: Wu Split-Gal4 Images (wu-split_*)" default="true">

        <inputFileSorter sortAlgorithm="LNumber" />

        <outputDirectory basePath="[\\dm10.janelia.priv\rubinimg|/groups/rubin/rubinimg]\rubin_wu_split\confocalStacks"
                         derivedFromEarliestModifiedFile="true"/>

        <plugins>

            <rowListener className="org.janelia.it.ims.tmog.plugin.imagedb.ImageDataPlugin">
                <property name="db.config.key" value="sage"/>
                <property name="family" value="$STATIC:rubin_wu_split"/>
                <property name="lab" value="$STATIC:none"/>
                <property name="line" value="$STATIC:Not_Applicable"/>
                <property name="display" value="$STATIC:false"/>
                <property name="base_path" value="$STATIC:/groups/rubin/rubinimg/rubin_wu_split/confocalStacks/"/>
                <property name="activation_line" value="${AD Line}-p65ADZp-in-${AD Landing Site}"/>
                <property name="binding_line" value="${DBD Line}-ZpGdbd-in-${DBD Landing Site}"/>
                <property name="gender" value="Gender$MAP:m=Male|f=Female|x=unknown"/>
                <property name="area" value="Area$MAP:b=Brain|v=Ventral Nerve Cord"/>
                <property name="age" value="Age"/>
                <property name="cross_number" value="Cross Number"/>
                <property name="anatomical_region" value="Brain Region"/>
                <property name="mounting_protocol" value="Tissue Mounting Protocol"/>
                <property name="tissue_orientation" value="Tissue Orientation"/>
            </rowListener>

            <sessionListener className="org.janelia.it.ims.tmog.plugin.SessionSummaryFileWriter">
                <property name="directory" value="\\dm10.janelia.priv\rubinimg\tmog\summaries\rubin_wu_split"/>
            </sessionListener>
        </plugins>

        <dataFields>

            <separator value="wu-split_"/>

            <text displayName="Cross Number"
                  required="true"
                  pattern="[0-9A-Za-z\-]++"
                  maximumLength="30">
            </text>

            <separator value="_"/>

            <!-- Activation Domain -->
            <text displayName="AD Line"
                  required="true"
                  pattern="[0-9A-Za-z]++"
                  maximumLength="5">
            </text>

            <separator value="-p65ADZp-"/>

            <validValueList displayName="AD Landing Site"
                            required="true">
                <validValue value="attP40" default="true"/>
                <validValue value="suHw-attP8"/>
                <validValue value="VK00027"/>
            </validValueList>

            <separator value="_"/>

            <!-- DNA Binding Domain -->
            <text displayName="DBD Line"
                  required="true"
                  pattern="[0-9A-Za-z]++"
                  maximumLength="10">
            </text>

            <separator value="-ZpGdbd-"/>

            <validValueList displayName="DBD Landing Site"
                            required="true">
                <validValue value="attP2" default="true"/>
            </validValueList>

            <separator value="_"/>
            <validValueList displayName="Reporter"
                            required="true">
                <validValue displayName="r1a: JFRC12-10XUAS-myr-GFP in attP2" value="r1a"/>
                <validValue displayName="r1b: pJFRC-IVS- myr-smGFP-HA-DARK in attP18, pJFRC-IVS-myr-smGFP-V5-DARK in su(Hw)attP8" value="r1b" default="true"/>
                <validValue displayName="r1c: pJFRC2-10XUAS-IVS-mCD8::GFP in VK00005" value="r1c"/>
                <validValue displayName="r1d: pJFRC101-20XUAS-IVS-Syn21-Shibire-ts1-GFP-p10 in VK00005" value="r1d"/>           
            </validValueList>

            <separator value="_"/>

            <validValueList displayName="Gender" required="true">
                <validValue displayName="f: Female" value="f" default="true"/>
                <validValue displayName="m: Male" value="m"/>
                <validValue displayName="x: Not Defined" value="x"/>
            </validValueList>

            <cvTermList displayName="Age" required="true"
                        serviceUrl="http://sage.int.janelia.org/sage-ws/cvs/age_remap"
                        displayNamePrefixedForValues="true"
                        markedForTask="true">
                <staticDefault value="A02"/>
            </cvTermList>

            <validValueList displayName="Area" required="true">
                <validValue displayName="b: Brain" value="b" default="true"/>
                <validValue displayName="v: Ventral Nerve Cord" value="v"/>
            </validValueList>

            <separator value="_"/>

            <number displayName="Sample Number" required="true"
                    minimumValue="1" maximumValue="99"  padFormat="20">
            </number>

            <separator value="_"/>
            <runTime datePattern="yyyyMMddHHmmssSSS"/>
            <separator value=".lsm"/>

            <!--
             These values are collected for the SAGE database but are not
             included as components of the file name (markedForTask="false").
             -->
            <validValueList displayName="Tissue Mounting Protocol" required="true"
                            markedForTask="false">
                <validValue value="Glycerol-Based Mounting"/>
                <validValue value="DPX Mounting" default="true"/>
            </validValueList>

            <cvTermList displayName="Tissue Orientation" required="true"
                        markedForTask="false"
                        serviceUrl="http://sage.int.janelia.org/sage-ws/cvs/tissue_orientation"
                        displayNamePrefixedForValues="false">
                <staticDefault value="unknown"/>
            </cvTermList>

            <validValueList displayName="Brain Region" required="true"
                            markedForTask="false">
                <validValue value="mushroom body"/>
                <validValue value="central complex"/>
                <validValue value="optic lobe"/>
                <validValue value="vlpr" default="true"/>
            </validValueList>

        </dataFields>

    </project>

</transmogrifierConfiguration>
