=== JaneliaSciComp/tmog/config/transmogrifier_config.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="inputFileFilterType">
        <xs:attribute name="patternString" type="xs:string"/>
        <xs:attribute name="patternGroupNumber" type="xs:positiveInteger"/>
        <xs:attribute name="excludeQueryUrl" type="xs:anyURI"/>
        <xs:attribute name="includeQueryUrl" type="xs:anyURI"/>
        <xs:attribute name="recursiveSearch" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="inputFileSorterType">
        <xs:attribute name="sortAlgorithm" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="outputDirectoryType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="path" type="pathType"/>
            <xs:element name="renameFieldValue" type="renameFieldValueType"/>
            <xs:element name="sourceFileModificationTime"
                        type="sourceFileModificationTimeType"/>
        </xs:choice>
        <xs:attribute name="basePath" type="xs:string"/>
        <xs:attribute name="derivedFromEarliestModifiedFile" type="xs:boolean"/>
        <xs:attribute name="fileModeReadOnly" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="pathType">
        <xs:attribute name="path" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="renameFieldValueType">
        <xs:attribute name="fieldDisplayName" type="xs:string"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="sourceFileModificationTimeType">
        <xs:attribute name="datePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="propertyType">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="pluginType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="property" type="propertyType"/>
        </xs:sequence>
        <xs:attribute name="className" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="pluginsType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="rowValidator" type="pluginType" />
            <xs:element name="rowListener" type="pluginType" />
            <xs:element name="sessionListener" type="pluginType" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="staticType">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="numberType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="staticDefault" type="staticDefaultType"
                        minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="minimumValue" type="xs:integer"/>
        <xs:attribute name="maximumValue" type="xs:integer"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="decimalType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="staticDefault" type="staticDefaultType"
                        minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="minimumValue" type="xs:integer"/>
        <xs:attribute name="maximumValue" type="xs:integer"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="textType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="staticDefault" type="staticDefaultType"
                        minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="minimumLength" type="xs:integer"/>
        <xs:attribute name="maximumLength" type="xs:integer"/>
        <xs:attribute name="pattern" type="xs:string"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="dateType">
        <xs:sequence>
            <xs:element name="sourceFileDateDefault" type="sourceFileDateDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="datePattern" type="xs:string"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="wellType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="formFactor" type="xs:integer"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="validValueType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="default" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="validValueListType">
        <xs:sequence>
            <xs:element name="sourceFileDefault" type="sourceFileDefaultType"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="validValue" type="validValueType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="prefix" type="xs:string"/>
        <xs:attribute name="suffix" type="xs:string"/>
        <xs:attribute name="copyable" type="xs:boolean"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="sharedForAllSessionFiles" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="pluginDataType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="format" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="fileModificationTimeType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="datePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="runTimeType">
        <xs:attribute name="datePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="fileExtensionType">
        <xs:attribute name="markedForTask" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="targetNameType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="fileRelativePathType">
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="markedForTask" type="xs:boolean"/>
        <xs:attribute name="visible" type="xs:boolean"/>
    </xs:complexType>

    <xs:simpleType name="matchType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="name"/>
            <xs:enumeration value="path"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="sourceFileDefaultType">
        <xs:attribute name="pattern" type="xs:string"/>
        <xs:attribute name="matchType" type="matchType"/>
    </xs:complexType>

    <xs:complexType name="sourceFileDateDefaultType">
        <xs:attribute name="pattern" type="xs:string"/>
        <xs:attribute name="matchType" type="matchType"/>
        <xs:attribute name="fromDatePattern" type="xs:string"/>
        <xs:attribute name="toDatePattern" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="staticDefaultType">
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="projectType">
        <xs:sequence>

            <xs:element name="inputFileFilter" type="inputFileFilterType" minOccurs="0"/>

            <xs:element name="inputFileSorter" type="inputFileSorterType" minOccurs="0"/>

            <xs:element name="outputDirectory" type="outputDirectoryType" minOccurs="0"/>

            <xs:element name="plugins" type="pluginsType" minOccurs="0"/>

            <xs:element name="dataFields" maxOccurs="1">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="separator" type="staticType"/>
                        <xs:element name="static" type="staticType"/>
                        <xs:element name="number" type="numberType"/>
                        <xs:element name="decimal" type="decimalType"/>
                        <xs:element name="text" type="textType"/>
                        <xs:element name="date" type="dateType"/>
                        <xs:element name="well" type="wellType"/>
                        <xs:element name="validValueList"
                                    type="validValueListType"/>
                        <xs:element name="pluginData" type="pluginDataType"/>
                        <xs:element name="fileModificationTime"
                                    type="fileModificationTimeType"/>
                        <xs:element name="runTime" type="runTimeType"/>
                        <xs:element name="fileExtension"
                                    type="fileExtensionType"/>
                        <xs:element name="targetName"
                                    type="targetNameType"/>
                        <xs:element name="fileRelativePath"
                                    type="fileRelativePathType"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="default" type="xs:boolean"/>
        <xs:attribute name="taskName" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="globalType">
        <xs:attribute name="minimumVersion" type="xs:string"/>
    </xs:complexType>

    <xs:element name="transmogrifierConfiguration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="global" type="globalType" minOccurs="0" maxOccurs="1"/>
                <xs:element name="project" type="projectType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== JaneliaSciComp/tmog/config/transmogrifier_config_flylight_collaborations.xml
<?xml version="1.0"?>

<transmogrifierConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="transmogrifier_config.xsd">

    <global minimumVersion="2.6.1" frameSizePercentage="95"/>

    <project name="FlyLight Collaborations" default="true">

        <inputFileSorter sortAlgorithm="LNumber" />

        <outputDirectory basePath="[\\dm10.isln.janelia.org|/groups/flylight]/flylight/collaborations/confocalStacks"
                         derivedFromEarliestModifiedFile="true"/>

        <plugins>

            <rowValidator className="org.janelia.it.ims.tmog.plugin.HttpResourceValidator">
                <property name="serviceUrl" value="http://sage.int.janelia.org/sage-ws/lines/flylight/${Line}.janelia-sage"/>
                <property name="testUrl" value="http://sage.int.janelia.org/sage-ws/lines/flylight/EXT_P_w_mC_ato_GAL4_3_6_14a.janelia-sage"/>
                <property name="errorMessage" value="There is no Fly Light line named '${Line}' in the SAGE database."/>
                <property name="clearCacheDuration" value="6000000"/><!-- 100 minutes -->
            </rowValidator>

            <rowValidator className="org.janelia.it.ims.tmog.plugin.WritableFromFileValidator">
                <property name="errorMessage"
                          value="The source file %s must be writable to allow meta data insertion before transfer."/>
            </rowValidator>

            <rowListener className="org.janelia.it.ims.tmog.plugin.imagedb.ImageSequencePlugin">
                <property name="db.config.key" value="sage" />
                <property name="image_number" value="urn:lsid:janelia.org:flylight_collaborations:image_number" />
            </rowListener>

            <rowListener className="org.janelia.it.ims.tmog.plugin.LsmMetaDataPlugin" >
            </rowListener>

            <rowListener className="org.janelia.it.ims.tmog.plugin.imagedb.ImageDataPlugin">
                <property name="db.config.key" value="sage"/>
                <property name="lab" value="$STATIC:flylight"/>
                <property name="family" value="$STATIC:flylight_collaborations"/>
                <property name="line" value="Line"/>
                <property name="gender" value="Gender"/>
                <property name="age" value="Age"/>
                <property name="chron_interval" value="Hours After Pupa Formation"/>
                <property name="area" value="Area"/>
                <property name="stain_antibody" value="Stain Antibody"/>
                <property name="mounting_protocol" value="Tissue Mounting Protocol"/>
                <property name="tissue_orientation" value="Tissue Orientation"/>
                <property name="effector" value="UAS Reporter"/>
                <property name="created_by" value="Imager"/>
                <property name="renamed_by" value="Renamer"/>
                <property name="class" value="Class"/>
            </rowListener>

            <sessionListener className="org.janelia.it.ims.tmog.plugin.SessionSummaryFileWriter">
                <property name="directory" value="[\\dm10.isln.janelia.org|/groups/flylight]/flylight/tmog/summaries/collaborations"/>
            </sessionListener>

        </plugins>

        <dataFields>

            <separator value="FLCO_"/>
            <runTime datePattern="yyyyMMddHHmmssSSS" />
            <separator value="_"/>
            <pluginData displayName="image_number"/>
            <separator value=".lsm"/>

            <!--
             These values are collected for storage but are not
             included as components of the file name (markedForTask="false").
             -->

            <text displayName="Line" required="true" displayWidth="150"
                  markedForTask="false">
            </text>

            <validValueList displayName="Gender" required="true"
                            markedForTask="false">
                <validValue value="Female"/>
                <validValue value="Male"/>
                <validValue value="unknown"/>
            </validValueList>

            <validValueList displayName="Age" required="true" markedForTask="false">
                <validValue value="undefined"/>
                <validValue value="Prepupa"/>
                <validValue value="Pupa"/>
                <validValue value="First Instar"/>
                <validValue value="Second Instar"/>
                <validValue value="Third Instar"/>
                <validValue value="Day 1-5"/>
                <validValue value="Day 6-10"/>
                <validValue value="Day 11-15"/>
                <validValue value="Day 16-20"/>
                <validValue value="Day 21-25"/>
                <validValue value="Day 26-30"/>
            </validValueList>

            <number displayName="Hours After Pupa Formation" required="false"
                    minimumValue="0" maximumValue="100"
                    markedForTask="false">
            </number>

            <validValueList displayName="Area" required="true"
                            markedForTask="false">
                <validValue value="Brain" />
                <validValue value="Salivary Gland" />
                <validValue value="Ventral Nerve Cord" />
            </validValueList>

            <cvTermList displayName="Stain Antibody" required="true"
                        markedForTask="false"
                        displayNamePrefixedForValues="true"
                        serviceUrl="http://sage.int.janelia.org/sage-ws/cvs/antibody">
                <staticDefault value="NC82"/>
            </cvTermList>

            <validValueList displayName="Tissue Mounting Protocol" required="true"
                            markedForTask="false">
                <validValue value="Glycerol-Based Mounting" default="true"/>
                <validValue value="DPX Mounting"/>
            </validValueList>

            <cvTermList displayName="Tissue Orientation" required="true"
                        markedForTask="false"
                        serviceUrl="http://sage.int.janelia.org/sage-ws/cvs/tissue_orientation"
                        displayNamePrefixedForValues="false">
            </cvTermList>

            <validValueList displayName="UAS Reporter" required="true"
                            markedForTask="false">
                <validValue value="UAS_IVS-mCD8_3_0007" default="true"/>
                <validValue value="UAS_mCD8_2_0006"/>
                <validValue value="LexAop_IVS-myr_3_0008"/>
            </validValueList>

            <validValueList displayName="Imager" required="true"
                            markedForTask="false">
                <validValue value="Aljoscha Nern"/>
                <validValue value="Alma Arnold"/>
                <validValue value="Amanda Cavallaro"/>
                <validValue value="Arnim Jenett"/>
                <validValue value="Chris Zugates"/>
                <validValue value="Christine Murphy"/>
                <validValue value="Donald Hall"/>
                <validValue value="Jennifer Jeter"/>
                <validValue value="Nirmala Iyer"/>
                <validValue value="Phuson Hulamm"/>
                <validValue value="Teri Ngo"/>
            </validValueList>

            <validValueList displayName="Renamer" required="true"
                            markedForTask="false"
                            sharedForAllSessionFiles="true">
                <validValue value="Aljoscha Nern"/>
                <validValue value="Alma Arnold"/>
                <validValue value="Amanda Cavallaro"/>
                <validValue value="Arnim Jenett"/>
                <validValue value="Chris Zugates"/>
                <validValue value="Christine Murphy"/>
                <validValue value="Donald Hall"/>
                <validValue value="Jennifer Jeter"/>
                <validValue value="Nirmala Iyer"/>
                <validValue value="Phuson Hulamm"/>
                <validValue value="Teri Ngo"/>
            </validValueList>

            <validValueList displayName="Class" required="false"
                            markedForTask="false">
                <validValue displayName="Screening" value="Screening" default="true"/>
                <validValue displayName="Rework" value="Rework"/>
            </validValueList>

        </dataFields>

    </project>

</transmogrifierConfiguration>
